CREATE DATABASE bankdb;

CREATE TABLE public.clients (
	client_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	address varchar(200) NULL,
	age int4 NULL,
	gender varchar(20) NULL,
	identification varchar(20) NOT NULL,
	"name" varchar(100) NOT NULL,
	phone varchar(20) NULL,
	"password" varchar(255) NOT NULL,
	status bool NULL,
	CONSTRAINT clients_pkey PRIMARY KEY (client_id),
	CONSTRAINT uk4t53k2na0fvk9pxg62n5a898i UNIQUE (identification)
);

CREATE TABLE public.accounts (
	account_number varchar(255) NOT NULL,
	client_id int8 NULL,
	initial_balance float8 NULL,
	status bool NULL,
	"type" varchar(255) NULL,
	CONSTRAINT accounts_pkey PRIMARY KEY (account_number)
);

CREATE TABLE public.movements (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	balance float8 NULL,
	"date" timestamp(6) NULL,
	"type" varchar(255) NULL,
	value float8 NULL,
	account_number varchar(255) NOT NULL,
	status bool NULL,
	CONSTRAINT movements_pkey PRIMARY KEY (id),
	CONSTRAINT fk2l2a6i00rsea2vcrmcbtp84rq FOREIGN KEY (account_number) REFERENCES public.accounts(account_number)
);

